import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashLoader from "./components/SplashLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IEEE IAS ISIMS SBC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SplashLoader>
          {children}
        </SplashLoader>
      </body>
    </html>
  );
}
